##远程自定义配置
galaxy:
  notCheckLoginUrl: /userLogin,/register,/getSmsVerificationCode,/findBackPasswor,/getInviteList,/getCategoryByParentId,/getUserListBySex,/error,/env/print,/swagger-ui.*,/static.*,/a2billing.*,/favicon.*,/webjars/springfox-swagger-ui.*,/v2/api-docs.*
  ucenter:
    version: v1.0

server:
  port: 9600

spring:
  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.100.17.12:3306/galaxy?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    maxLifetime: 1800000
    maximumPoolSize: 15
  redis:
    # 指定redis 使用2库
    database: 2
    password: 123456
    host: 47.100.17.12
    port: 6379
    timeout: 6000  # 连接超时时长（毫秒）
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接

log:
  path : galaxy/ucenter/logs
  level : info
  ibatis : DEBUG

# 直接放行URL
ignore:
  urls:
  - /*/**
  - /*/info/*
  - /*/**

file:
  staticAccessPath: /ucenter/upload/**
  uploadPath: /home/upload/
  #uploadPath: E:\upload

# 注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

## 允许/actuator/bus-refresh接口被外部调用
management:
  endpoints:
    web:
      exposure:
        include: "*"

# mybaits配置
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml

feign:
  hystrix:
    enabled: true