##远程自定义配置
galaxy:
  notCheckLoginUrl: /userLogin,/register,/getSmsVerificationCode,/findBackPasswor,/getInviteList,/getCategoryByParentId,/getUserListBySex,/error,/env/print,/swagger-ui.*,/static.*,/a2billing.*,/favicon.*,/webjars/springfox-swagger-ui.*,/v2/api-docs.*
  ucenter:
    version: v1.0

server:
  port: 9996
  servlet:
    context-path: /

spring:
  # 数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
    url: jdbc:mysql://:3306/?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    maxLifetime: 1800000
    maximumPoolSize: 15
  redis:
    password:
    host: 172.17.14.61
    port: 6379
    timeout: 6000  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

log:
  path : galaxy/ucenter/logs
  level : info
  ibatis : DEBUG

# 直接放行URL
ignore:
  urls:
  - /*/**
  - /*/info/*
  - /*/**

file:
  staticAccessPath: /ucenter/upload/**
  uploadPath: /home/upload/
  #uploadPath: E:\upload

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

## 允许/actuator/bus-refresh接口被外部调用
management:
  endpoints:
    web:
      exposure:
        include: "*"

# mybaits-plus配置2
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml,classpath:/mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true

feign:
  hystrix:
    enabled: true